# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"

  before_all do
    if ENV["CI"] then
      create_keychain(
        name: "GithubActionKeychain",
        password: ENV["MATCH_PASSWORD"],
        default_keychain: true,
        unlock: true,
        timeout: 3600,
        lock_when_sleeps: true,
        add_to_search_list: true
      )
      match(
        keychain_name: "GithubActionKeychain",
        keychain_password: ENV["MATCH_PASSWORD"],
        type: "appstore",
        app_identifier: "me.dutour.mathieu.Bruit-Blanc",
        readonly: true
      )
    else
      match(type: "appstore")
    end
  end

  lane :beta do
    increment_build_number(build_number: ENV["BUILD_NUMBER"], xcodeproj: "Bruit Blanc.xcodeproj")
    build_app(scheme: "Bruit Blanc", xcargs: "\"FASTLANE_BUILD\"=\"YES\"")
    if ENV["CI"] then
      upload_to_testflight(skip_waiting_for_build_processing: true)
    else
      upload_to_testflight()
    end
  end

  after_all do
    if ENV["CI"] then
      delete_keychain(
        name: "GithubActionKeychain"
      )
    end
  end
end
